name: "Test notify reusable"

on: 
  workflow_dispatch:
    inputs:
      text:
        required: true
      channel:
        required: true
      token:
        required: true

jobs:
  notify:
    name: Notify slack
    uses: transferwise/actions-slack-notify/.github/workflows/run.yml@main
    with:
      text:    ${{ inputs.text }}
      channel: ${{ inputs.channel }}
      token:   ${{ inputs.token }}
