name: "Test notify reusable"

on: 
  workflow_dispatch:
    inputs:
      text:
        type: string
        required: true
        default: "test"
      channel:
        type: string
        required: true
        default: "@pavel.dvoinos"
      token:
        type: string
        required: true

jobs:
  notify:
    name: Notify slack
    uses: transferwise/actions-slack-notify/.github/workflows/run.yml@main
    with:
      text:    ${{ github.event.inputs.text }}"
      channel: ${{ github.event.inputs.channel }}
      token:   ${{ github.event.inputs.token }}
